chore(build): set up an end-to-end test to check deployment

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -25,7 +25,7 @@ jobs:
         run: |
           npm run lint
 
-  build_and_test:
+  unit_tests:
     runs-on: ubuntu-20.04
     strategy:
       matrix:
@@ -55,8 +55,8 @@ jobs:
           flag-name: nodejs-${{ matrix.node }}
           parallel: true
 
-  finish_tests:
-    needs: build_and_test
+  finish_unit_tests:
+    needs: unit_tests
     runs-on: ubuntu-20.04
     steps:
       - name: Coveralls Finished
@@ -65,8 +65,68 @@ jobs:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           parallel-finished: true
 
+  e2e_tests:
+    needs: unit_tests
+    runs-on: ubuntu-20.04
+    steps:
+      - uses: actions/checkout@v1
+
+      - name: Use Node.js v12.x
+        uses: actions/setup-node@v1
+        with:
+          node-version: v12.x
+
+      #- name: debug deploy_package
+      #  uses: actions/bin/debug@master
+
+      - name: run end-to-end deploy test
+        env:
+          AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        run: |
+          cd "$GITHUB_WORKSPACE/examples/basic"
+          npm i
+          npm run deploy
+          # get the APIG endpoint URL:
+          APIG_URL=$(./node_modules/.bin/serverless info --aws-profile serverless | sed -nr 's#^.*(https://.+/dev)/png$#\1#p')
+
+          # CURL to some known good endpoints expecting 200:
+          function TEST_HTTP ()
+            {
+              URL_PATH=$1
+              if [[ -e "$URL_PATH" ]]; then
+                echo "path not specified"
+                return 1
+              fi
+              HTTP_CODE=$(curl -s -w '%{http_code}' --compressed --output /dev/null "$APIG_URL/$URL_PATH")
+              if [[ "$HTTP_CODE" = "200" ]]; then
+                echo "/$URL_PATH succeeded"
+              else
+                echo "/$URL_PATH failed with code $HTTP_CODE"
+                exit $HTTP_CODE
+              fi
+            }
+
+          TEST_HTTP png
+
+          TEST_HTTP jpg
+
+          TEST_HTTP binary/glyphicons-halflings-regular.woff2
+
+          TEST_HTTP binary/subdir/png.png
+
+      - name: destroy serverless stack
+        # Run this step even if the prior one failed (to clean up)
+        if: ${{ always() }}
+        env:
+          AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        run: |
+          cd "$GITHUB_WORKSPACE/examples/basic"
+          npm run destroy
+
   deploy_package:
-    needs: finish_tests
+    needs: e2e_tests
     runs-on: ubuntu-20.04
     steps:
       - uses: actions/checkout@v1
